### ISSUE TITLE
Mitteilungen von Usern (Rücksprache)

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#1]
@Arantis 

Ist die folgende E-Mail bei dir eingegangen?

> Hallodri tells you, "hatte ich, eine mail nanmes Ã¼bersetzungen und anregungen oder so, von chris@schlagmichtod.de, anfang der woche oder wma WE glaubich"

**Comment by Arantis** [comment]
Ja ist angekommen in in "Bearbeitung". Derzeit mit dem Patch und "Umstrukturierungen im Repo zu tun (Prio 1)

**Comment by tyras2** [comment]
Super
