### ISSUE TITLE
Newsletter-System einbinden

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#11]
Kennt Ihr ein kostenfreies Newslettersystem? Beruflich verwende ich persönlich cleverreach.de, das ist schon recht gut. Aber nur bis 1000 E-Mails pro Monat kostenfrei. Sollte jedoch erstmal reichen..

Alternative?

**Comment by Rodrigez01** [comment]
wie haben eins auf der Arbeit .. 
ansonsten "könnte" contao das auch .. ein open-source-cms 
das wo strandpizzeria drauf läuft .. hatte ich dir gezeigt ..

**Comment by tyras2** [comment]
@Rodrigez01 Kannst du dich da mal schlau machen?

**Comment by Arantis** [comment]
Von Newsletter Systemen habe ich wenig Ahnung.
Frage ist hier, wie wir dir User erfassen. Heißt sie müssten sich registrieren... beim Account erstellen?
was ist mit denen die schon registriert sind?

Newsletter heißt Datenschutzerklärung :) nur zur Info

**Comment by Rodrigez01** [comment]
10-15€ würde ich übernehmen ..

**Comment by tyras2** [comment]
Wie besprochen nehmen wir erstmal Cleverreach.. allerdings muss ich es noch fertig einrichten. Danach veröffentlich wir es dann entsprechend

**Comment by tyras2** [comment]
Bevor wir das posten. @Rodrigez01 willst du das vielleicht übernehmen, oder kenn ihr jemanden, der in Social-Media fit ist und die Zeit hat, da was schönes aufzubauen?

**Comment by tyras2** [comment]
Newsletter-System ist final auf der HP
