### ISSUE TITLE
Barde

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#13]
@Arantis 

Wollen wir die Stelle für einen Barden auch auschreiben? Oder eine andere Idee?

**Comment by Arantis** [comment]
Bin ich mir unsicher. Derzeit mit dem IRC für Tyras, Rodrigez und mich genug? 
Sollte INgame jemand vorhanden sein?
Denke da eher an Event Barden, aber bin mir nicht sicher was die beste lösung ist.

Wir wollen grundsätzlich auch spielen. Heißt ein Barde könnte ja fast nicht spielen :-P

**Comment by Rodrigez01** [comment]
Ich denke ein "Notfall" Barde wäre ok .. 
aber der IRC würde reichen, denke ich ..

**Comment by tyras2** [comment]
@Arantis @Rodrigez01 Bin mir da nicht ganz sicher. 

Einen Ansprechpartner der auch reagiert, wenn er Online ist, ist nicht verkehrt. Helferlein ist immer Online, und für die Spieler "Einfach da", ohne das er was macht. Zumal wir nicht immer im IRC sind und alle Anfragen mitbekommen.

So ein Barde unterhält eben die Leute und hat immer ein offenes Ohr. Wir wollen ja zurück zu den guten alten Zeiten. Da gehört ein Barde wie ich finde schon dazu.

Am Ende fallen dann wieder alle Events auf dich zurück, und wir haben weniger Zeit uns für die Entwicklung des Servers zu kümmern.

Was spricht dagegen, einen mit Probezeit ohne Rechte einzuarbeiten, und schauen, wie er sich schlägt? Wenn nach einem Aufruf kein passender dabei ist, ist es eben so..

**Comment by Rodrigez01** [comment]
ein Barde war auch damals nicht immer da,
aber wenn du es willst, würd ich s machen, ob ich nun im irc bin oder online.. das ist wurst ..
natürlich nur ohne rechte ...

**Comment by tyras2** [comment]
Natürlich ist der Barde nicht immer on, aber wenn er on ist, dann ist er auch erreichbar. Im Gegensatz zu unserem Helferlein.

Ein Barde sollte natürlich auch Barde heissen, und muss im Gegenzug alle seinen sterblichen Accounts abgeben. Uns etwas RPG sollte er auch natürlich beherrschen. Die Frage ist, ob du das willst?

**Comment by Rodrigez01** [comment]
bis auf das ich meine, wie sagst du, sterblichen Accounts abgebe, würde ich das wollen .. ich denke auch das abgeben hat sich erübrigt. denn wenn ein "Sterblicher Account" über Helferlein antwortet, macht das genau so wenig Sinn :) ??

**Comment by SaschaOFC** [comment]
Es soll ja nicht bei einem Rechtefreien Barde bleiben, denn so kann er keinerlei Events starten.. so macht er wenig Sinn.

Helferlein steuere ich über IRC, nicht über einen Account. Und darüber machen wir auch keine Events, sondern sind nur Kontaktperson in Problemfällen. Das hab mit dem Barde nichts zu tun..

Aber ich merke schon, es wird kompliziert ;-)

**Comment by tyras2** [comment]
Es soll ja nicht bei einem Rechtefreien Barde bleiben, denn so kann er keinerlei Events starten.. so macht er wenig Sinn.

Helferlein steuere ich über IRC, nicht über einen Account. Und darüber machen wir auch keine Events, sondern sind nur Kontaktperson in Problemfällen. Das hab mit dem Barde nichts zu tun..

Aber ich merke schon, es wird kompliziert ;-)

**Comment by Rodrigez01** [comment]
Ja das sehe ich genau so .. es wird Kompliziert ..
Die Frage ist, wieviel Vertrauen wir uns entgegen bringen .. 
ich würde keiner meiner Chars die ich in arbeit habe mit Barden/Guide-Hilfe Leveln wollen!!!
Die Frage ob Arantis mir meinen alten Rodrigez zusammen schuster würde, war im Rahmen der Reaktivierung UND vorallem, weil da viele Erinnerungen dran hängen,
z.B. 
1. Mit dem Char habe ich meine Damalige Freundin kennen gelernt.
2. Viele schöne Tage die ich mit Ihm erleben durfte.
3. der Tod und das Onlinegedenken von Gammy
usw ...
aber wir haben uns wirklich falsch verswtanden wenn ihr denken würdet, dass ich einen char "einfach" haben will ...

@ Tyras, ich merke, dass wir schon jetzt einige Probleme haben .. die sollten wir möglichst heute abend aus dem Weg räumen um unms auf das wesentliche konzentrieren zu können :)

**Comment by tyras2** [comment]
Eine Diskussion mit einer Meinungsverschiedenheit ist doch kein Problem, sonder eher eine kostruktive Kritik. So soll es ja sein ;-)

Es geht einfach darum, das in meinen Augen kein Barde mit Rechten einen Sterblichen Account auf dem Server haben darf. Das war auch auf den alten Servern unter 3DO und MDO so.

Der Grund dafür ist eigentlich recht simpel: Es kann immer Konfliktpotential gegenüber andere Spieler geben. Sollte herrauskommen, das Barde X auch einen sterblichen Account Y hat, muss man sich immer mit dem Thema Korruption befasst machen.

Wenn der Barde keinen hat, ist das Thema schon wieder vom Tisch, und alles ist in Ordnung.

**Das heisst jetzt nicht, das ich dir das unterstelle, im Gegenteil!**

**Comment by tyras2** [comment]
Wir unterbrechen die Disskusion jetzt hier erstmal. Solange wir noch an vielen Stellschrauben drehen, stellen wir das mal hinten an und befassen uns zum späteren Zeitpunkt damit.. Arantis hatte ja schon angedeutet, das es hier erstmal keinen Handlunsgbedarf besteht. Einverstanden?

**Comment by Rodrigez01** [comment]
Damals war es aber auch so, dass es mehr Server gab, auf den die guides/barden selber spielten :P

**Comment by tyras2** [comment]
> Damals war es aber auch so, dass es mehr Server gab, auf den die guides/barden selber spielten :P

Mag sein, diesen Fall haben wir so hier aber nicht. Ist ja auch egal.. siehe Kommentar oben.

**Comment by tyras2** [comment]
Meridian59.de sucht Verstärkung

Als Bindeglied zwischen den Admins und den Spielern sucht Meridian59 Deutschland ab sofort einen ehrenamtliche Barden, um den Support im Spiel zu verbessern.

Deine Primäre Aufgabe wird es sein, die Fragen der Spieler rund um Meridian59 zu beantworten. Dazu wirst du Events planen, und mit Rücksprache der Admins durchführen. Besonderen Wert legen wir auf:

- Lange Erfahrung in Meridian59
- Besonderes Kenntnisse im Rollenspiel
- Regelmäßige Aktivität

Wenn du Interessiert bist, Meridian59.de zu Unterstützen, so melde dich doch bitte bei per E-Mail (support@meridian59.de) bei uns. Für Rückfragen stehen wir dir gerne zur Verfügung.

Aranits
