### ISSUE TITLE
Übersetzungsfehler II (Sammelthread)

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#14]
Alle Todesmeldungen bitte in Fett ausgeben

**Comment by tyras2** [comment]
@Arantis Kannst du mal schauen, ob die Avar-Fede Quest richtig übersetzt ist? Es gibt einmal die Quest mit dem Neruditklumpen, und einmal die, einen Shamanen zu töten. Ich glaube, es wurden beide so übersetzt, einen Shamanen zu Töten?

**Comment by tyras2** [comment]
> Dieses Lied ermöglicht es den Zuhörern schneller ihr Mana zurückzugewinnen. Man benötigt einen Diamanten und einen rohen, ungebrochenen Seraphen.

Ändern in 

> Dieses Lied ermöglicht es, den Zuhörern schneller ihr Mana zu regenerieren. Man benötigt einen Diamanten und einen ungeschliffene Seraph.

**Comment by tyras2** [comment]
@Arantis Die Jala Schüler Quest wurde glaube ich falsch Übersetzt. Parrin fragt dich, ob man "Gut" oder "Schlecht" gesungen hat. Man muss wohl mit "schrecklich" antworten. Hier muss man eigentlich "Schlecht" antworten. Kannst du das mal überprüfen?

**Comment by Rodrigez01** [comment]
Schachquest, Kein Name der Empfänger

**Comment by Rodrigez01** [comment]
Fehler in der Übersetzung Verzauberte Waffen
"wenn es vielleicht ein leuchten Rand in Spiele und Turniere bieten."

**Comment by Rodrigez01** [comment]
Blitzwand
Falsche Zutaten
Erschafft eine Wand aus Elektrizität. Jeder, der dieses Feld betritt, wird mehr als nur Donner spüren.Benötigt Yxrl-Saft und Kräuter

**Comment by tyras2** [comment]
@Rodrigez01 

Ich glaube es ist besser für Arantis, wenn du einmal den falschen, und dann den richtigen Text angibts. So wie hier https://github.com/Arantis/Meridian59_112/issues/2

**Comment by Rodrigez01** [comment]
wenn ich das mit dem Git- endlich hin bekomme, wollt ich das selber Übersezten .. dann hat Antaris nicht zu viel Arbeit ..

**Comment by tyras2** [comment]
> wenn ich das mit dem Git- endlich hin bekomme, wollt ich das selber Übersezten .. dann hat Antaris nicht zu viel Arbeit ..

@Rodrigez01 Das wäre natürlich noch besser ;-)

**Comment by tyras2** [comment]
> This parchment encodes 1 mystic incantation.  The runic script averages 45 spellpower.

Ändern in

>

**Comment by tyras2** [comment]
> Your standing with The Orcs has decreased
Your standing with The Peet-Seeeep Avar Clan has increased
Your standing with The Kyip-Kyip-Kreeet Avar Clan has increased
Your standing with The Chyup-Tewee Avar Clan has increased

Ändern in

>

**Comment by tyras2** [comment]
> Du plünderst einige Dinge von der Leiche, und findest  XY Schillinge.

Zwischen "findest" und "XY Schilinge" ist ein Leerzeichen zuviel

**Comment by tyras2** [comment]
> Du findest nichts besonderes was du plündern kannst, erhälst dafür aber  XY Schillinge.

Zwischen "aber" und "XY Schillinge" ist ein Leerzeichen zuviel.
Erhälst => Erhältst

> Du findest nichts besonderes was du plündern kannst, erhältst dafür aber  XY Schillinge.

**Comment by tyras2** [comment]
> Du nimmst ein paar Gegenstände von der Leiche auf , aber wirst behindert, alles aufzunehmen.

Ändern in

> Du nimmst ein paar Gegenstände von der Leiche auf, wirst aber behindert, alles aufzunehmen. Vielleicht kannst du nichts mehr tragen?

**Comment by tyras2** [comment]
>Zauberkraft für XY ist 99.

Ändern in

>Deine Zauberkraft für XY beträgt XY%.

**Comment by tyras2** [comment]
> Tyras murmelt etwas vor sich hin und deutet auf sich selbst.

Habe allerdings auf einen anderen Charakter gezaubert. Bitte überprüfen!

**Comment by tyras2** [comment]
> Razziano murmelt etwas vor sich hin und deutet auf Die Holunderbeere.
Razziano murmelt etwas vor sich hin und deutet auf mehr Holunderbeeren.

Oben wenn ich auf eine Holunderbeere zauber, unten wenn ich auf mehrere Zauber.
Ändern in:

> Razziano murmelt etwas vor sich hin und deutet auf Die Holunderbeere.
Razziano murmelt etwas vor sich hin und deutet auf mehrere Holunderbeeren.

**Comment by tyras2** [comment]
>Der Angriff von XY wird ausgewichen
Der Angriff von XY trifft nicht 
Der Angriff von XY wird geblockt
Der Angriff von XY wird parriert

Hier fehlen überall Punkte am Ende. Bei allen anderen Mittielung ist einer am Ende. Sollte also hier auch einer sein.
Parrieren nur mit einem R

>Der Angriff von XY wird ausgewichen.
Der Angriff von XY trifft nicht .
Der Angriff von XY wird geblockt.
Der Angriff von XY wird pariert.

**Comment by tyras2** [comment]
>Du kannst den motivierenden Song, gespielt von XY's nicht mehr hören.

Da macht das semikolon kein Sinn, oder? 

>Du kannst den motivierenden Song, gespielt von XY, nicht mehr hören.

**Comment by tyras2** [comment]
> XYs motivierender Song, lässt dich, deine Müdigkeit vergessen.

Hier macht ein semikolon sinn, es gibt aber keines.. Ändern in:

>XY's motivierender Song, lässt dich, deine Müdigkeit vergessen.

**Comment by Arantis** [comment]
@Arantis - Spezial Waffen Attribute Checken!

**Comment by Rodrigez01** [comment]
Buch, Cor North,
>Die Bewohner der zerklüfteten Berge sehen sich selbst als eine eigene Kultur - unabhängig vomRest von Meridian. Ihr Kampf um Unabhängigkeit gegen das, was sie als erzwungene Herrschaft der Regierungen in Tos und später Barloque erachten, hat sie bereits zu drei Kriegen während offenerRebellionen gegen die Krone geführt.


>Die Bewohner der zerklüfteten Berge sehen sich selbst als eine eigene Kultur - unabhängig vom Rest von Meridian. Ihr Kampf um Unabhängigkeit gegen das, was sie als erzwungene Herrschaft der Regierungen in Tos und später Barloque erachten, hat sie bereits zu drei Kriegen während offener Rebellionen gegen die Krone geführt.

**Comment by tyras2** [comment]
>Dies ist ein Schmuckstück der Ältesten, welches ihnen von den Göttern gegeben wurde.Die Legende besagt, dass das Schmuckstück die Kraft besitzt die Grundwerte der Sterblichen zu ändernDie Ältesten werden dich sicher belohnen, wenn du es ihnen zurückbringst.

Ändern in

> Dies ist ein Schmuckstück der Ältesten, welches ihnen von den Göttern gegeben wurde. Die Legende besagt, dass das Schmuckstück die Kraft besitzt die Grundwerte der Sterblichen zu ändern. Die Ältesten werden dich sicher belohnen, wenn du es ihnen zurückbringst!

**Comment by Arantis** [comment]
Okay soweit alles erledigt!
Schachbrett weiß ich nicht was da gemeint ist, da habe ich keinen Anhaltspunkt. Bei der Wryn wäre dann die "Korrektur" super, dann könnte ich das direkt nutzen.

Ein paar Sachen kann man einfach so vorerst nicht ändern wie z.B. Holunderbeere(n). Denn der nimmt sich den Namen von den Reagenzien und da heißt es die Holunderbeere. Sonst müsste man die Reagenzien alle noch einmal durch schauen aber das wurde so wie damals eingebaut. Teilweise wurden da die Sätze geändert das es z.T. nicht so super klingt aber das geht so zumindest nicht anders.

Habe auch soweit alle Reports per Ingame Mail etc. abgearbeitet und würde es dann soweit belassen und dann morgen das Repo sowweit fertig machen und dann gehen sämtliche sonstige Übersetzungen dann in den nächsten Patch rein

**Comment by tyras2** [comment]
Super, vielen Dank für die mega Arbeit! Dann machen wir das hier zu, und eröffnen einen neuen Issue..
