### ISSUE TITLE
Event: Göttliches Wochende!

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#15]
Aufgrund der Zahlreichen neuen Charaktere im Lande, haben sich die 5 Ratsmiglieder Meridians dazu entschlossen, ein Göttliches Wochende auszurichten. 

Dazu wird Drechx die Chancen, ein Lebenspunkt zu erhalten, verdoppeln. Cylill und Alzahakar, letztere bekannt als der mächtigste Zauberer des Königreiches, werden die Chancen Zauberfertigkeiten sowie Waffenfertigkeiten zu ergattern, ebenfalls drastisch erhöhen.

Das Event findet von Freitag, den 26.02 bis einschließlich Sonntag, den 28.02 statt.

> **Das Ziel: Alle leute, die neu angefangen haben, durch einen besseren Charakter an den Server zu binden.**

**Comment by Arantis** [comment]
Okay hiermit bestätigt ich kann den Item drop, Money drop, HP Chance und % Chance steigern.
Wie hoch? Gefühlt würde ich sagen, wenn wir 2,5 Tage machen sollten wir 150% nehmen, denn osnst sind 200 zu viel.

Loot und Money erhöhen für das Monster event was wir dann auch mit in die News schreiben!
Monster event Samstag oder sOnntag abend. Oder beide Abende für Leute die wenig Zeit haben? Wird nichts wildes, einfach 30-60 Minuten random monster spawn auf dem fridi?!

**Comment by tyras2** [comment]
**Neuer Text:**

Göttliches Wochende! 

Aufgrund der Zahlreichen neuen Charaktere im Lande, haben sich die 5 Ratsmiglieder Meridians dazu entschlossen, ein Göttliches Wochende auszurichten.

Dazu wird Drechx von Freitag (26.02) bis einschließlich Sonntag (28.02) die Chancen, ein Lebenspunkt zu erhalten, deutlich steigern! Cylill und Alzahakar, letztere bekannt als der mächtigste Zauberer des Königreiches, werden die Chancen Zauberfertigkeiten sowie Waffenfertigkeiten zu ergattern, ebenfalls drastisch erhöhen.

Zum Abschluss wird es am Sonnabend ein tolles Monster-Event geben. Lasst euch Überraschen!
