### ISSUE TITLE
Änderungen

### ISSUE THREAD

**Issue by Arantis** [Arantis/Meridian59_112#16]
112 / 200 Changes in config/setting

hold.kod
viCastTime hold = 0

truce.kod
enabled/accessible = true

settings.kod
pbBuffOthersInSafeZones = TRUE in settings to false
pbPvPOptOutEnabled = FALSE

Red Pens

**Comment by Arantis** [comment]
Panzermolche auf -100 Karma als Gleichberechtigung zu +100 Karma
100 Stacks erhöhen auf 200 mindestens (600 war zu krass). Aber mit vielen Ringen Säbel etc. zu schnell voll.
Zerbrechen wieder aktivieren?
Logon Bonus TP okay?

**Comment by Arantis** [comment]
uuund noch Ausgleich für 150 HP monster für Qoris. Gibt nur + Karma (Kriipa z.B.=)

**Comment by tyras2** [comment]
Your current Unheilige Lösung enchantment adds 20% Heiliger Widerstand.

=> An Delerium weitergeben, bitte bei nächste Update daran denken..

**Comment by tyras2** [comment]
@Arantis Bitte folgende Probleme bearbeiten:

* Das Schild in der Raza GMH hat Probleme mit Umlaute
* Das Warevent ist Hardcoded und nicht so einfach zu Übersetzen (Laut deiner Aussage)
* Die "Verkümmerte Zwerg Quest" soll wohl nicht gehen, bitte prüfen

**Comment by Arantis** [comment]
(23:09:47) Server112Chat: 112: Finn broadcasts, " (\/) The Mages (\/)   na ja.. verlöden statt verblöden ist nicht wirklich besser *g*"
(23:10:07) Server112Chat: 112: Kickersen broadcasts, "0==|######> McSteele <######|==0    "verblonden" wäre witziger gewesen ..."
(23:10:12) Server112Chat: 112: Brendel broadcasts, "dafür gibt es neue ... todesbündniss soll lila/fese kosten und nicht fese/blut wie in der beschreibung"


<==== Da habe ich reingeschaut und sehe es für beide Sachen im Code richtig!? Sehe nirgends verlöden und auch Todesbündniss zeigt im eng und de dasselbe an reas an?

**Comment by Arantis** [comment]
nochmal geschaut wegen deathlink... verstehe die Aussage nicht... ?!?
      plReagents = Cons([&ShamanBlood,1],plReagents);
      plReagents = Cons([&DarkAngelFeather,1],plReagents);

**Comment by Arantis** [comment]
okay  gefunden :-)
dement_already_enchanted = de "Diese arme Seele ist schon verlödet." <== next patch

**Comment by Arantis** [comment]
Waffenruhe PvE in die Beschreibung!!

**Comment by tyras2** [comment]
Faction-Loose für Farbige Charakter deaktivieren? 

So auch aktiv auf 103/105..

**Comment by Arantis** [comment]
Hold meditation deaktivieren im code

**Comment by Arantis** [comment]
Richter --> Begnadigung nur auf orange Text auf Schild bei Caramo ändern

**Comment by tyras2** [comment]
PrincessShield_name_rsc ANSI Format?

**Comment by tyras2** [comment]
- [ ] Richter ist erledigt

**Comment by tyras2** [comment]
Ancient trinket prüfen, hier fehlt text (wird abgeschnitten).. ggf. Text kürzen

**Comment by tyras2** [comment]
Das Warevent ist Hardcoded und nicht so einfach zu Übersetzen (Laut deiner Aussage) => Bitte prüfen

**Comment by tyras2** [comment]
**duskrat.lkod** gibt Umlaute nicht richtig aus, bitte umkonvertieren

**Comment by Arantis** [comment]
Statue test

**Comment by Arantis** [comment]
Patch 1.8.0 und OGRE Update

FAREN ZERSTÖREN ???

Salve Meridian,
dieses Update kombiniert Updates für den Server sowie kleinere Updates für den OGRE Client (Update 1.0.4.6). Zu erwähnen ist ein neuer Weg um Zaubersprüche auszuführen. In dem Monster getötet werden, kann man ungebundene Energie sammeln und die zum Zaubern verwenden. Diese ungebundene Energie kann dazu genutzt werden die Zauber auszuführen, ohne Reagenzien und Ausdauer nutzen zu müssen und Fehlversuchen zu erleiden. Außerdem erhöht es die Zauberstärke (+20) und die Chance sich zu verbessern. Dieses Update ist dazu gedacht, dass die Spieler mehr Ihrer Zaubersprüche zaubern und testen während sie den Charakter leveln (HP's und Waffen) ohne auf die Reagenzien zu achten, die sonst währendessen mitgeschleppt werden müssten. Dies mag einen Einfluss auf die "Server Wirtschaft" da der Loot sich bislang nicht geändert hat. Dieser Loot wird vermutlich in naher Zukunft angepasst, so dass Monster in der Zukunft weniger Schillinge und Reagenzien fallen lassen.

OGRE Client Änderungen
- es wurden ein paar neue höher auflösende Texturen hinzugefügt
- Fix: Problem bei dem User im Welcome Screen hängen blieben nachdem der Client geschlossen wurde
- Fix: Spieler blieben noch eingeloggt für eine gewisse Zeit nach verlassen des Spiels
- Fix: Dunkle Höhle und Qor Tempel Ausgänge
- Neu: balance (Kontostand wird bei der Bank angefragt), time (In-Game Zeit) und appeal (Nachricht an die Barden/Admins/Guides)
- Fix: magische Gegenstände werden nun richtig mit unterschiedlichen Farben und Beschreibungen angezeigt

Generelle Änderungen
- Fix: Moxal Quest Fehler behoben
- Man kann nun nicht mehr auf sich nicht bewegende "Monster" (Brombeerwand, Waldschart, ...) Verleiten zaubern.
- Stille wurde deaktiviert um ihn zu veränden und interessanter zu machen
- Grundwurm Larve aus dem Tal von Illeria entfernt (nur noch Pilzwesen)
- Optionaler Zeitstempel eingefügt im klassischen Client. Kann in den Einstellungen aktiviert/deaktiviert werden.
- NEU: Chat Log wird nun gespeichert, wenn man das Spiel verlässt ohne den Client komplett zu schließen (leider ohne Farben und Styles)
- NEU: Ein paar neue Admin Zauber, die bei Events nützlich sind 
- NEU: Kill/Tot Statistik für Frenzies. Statistik kann während der Frenzy angezeigt werden und nachträglich von den admins als log gespeichert werden
- 2 Sekunden Verzögerung bei der Plattform nach Brax eingestellt bevor die Plattform sich beweg
- Aktive Quests bleiben nun nach Updates (z.B. es wird das Säbelkampf Quest gestatet und der Server startet für ein Update neu, dann wird nun das Quest weiterhin erhalten bleiben)
- Ausstieg/Logout Geist Zeit regeneriert nun während der Spieler eingeloggt ist und sich außerhalb von einem sicheren Raum befindet. Es gibt aber eine 5 Sekunden Verzögerung nach dem Einloggen/Ausstieg bevor die Zeit regeneriert.
- Die Map des verrückten Wissenschaftlers auf Ko'Catan ist nun ein sicherer Ort
- Kosten der Reagenzien für Bluterbe erhöht, aber der Zauber kann mehrfach auf einem Gegenstand gezaubert werden. Lähmen/Blenden/Beseitigen Gegenstände können nicht mehrfach verzaubert werden, und extra starke Kombinationen werden wenn nötig entfernt.
- Mana entziehen Verzauberung wurde nun beim Bluterbe hinzugefügt
- NPC Menge die, die Spieler mit der PvP opt-out Option volltexten wurden verringert
- Ein "line of sight check" wurde für Eisstern und Feuersturm Attacken eingebaut, um zu verhindern das die Attacken durch Wände funktionieren.
- Ein paar Performance Verbesserungen und kleinere nicht sichtbare Fehlerbehebungen
- Ein paar Übersetzungsfehler (danke für alle Zusendungen)

Ungebundene Energie
- Spieler haben eine neue "Ungebundene Energie" Anzeigeleiste unter den Widerständen (Grundwerte Menü). Wird ggf. noch einmal verschoben
- Ungebundene Energie erhält man beim Töten von Monstern (Menge basiert auf dem Monster Level, Spieler HP, Magie und die Entfernung zum Monster)
- Ungebundene Energie kann dazu genutzt werden um Zauber auszuführen und wird 1:1 berechnet wie bei den Trainingspunkten. (Zauber benötigt 50TP zum verbessern bedeutet 50 Energie zum zaubern)
- Keine Reagenzien, Ausdauer oder Mana werden benötigt, wenn man diese Ungebundene Energie nutzt
- Zauber die so gezaubert werdeb haben +20 Zauberkraft, können nicht fehlschlagen und haben eine größere Chance zu steigern
- Spieler können bis zu 500 Ungebundene Energie speichern. Die Ungebundene Energie beginnt nach 30 Sekunde (nach Erhalt) damit zu verfallen. Jeder weitere Erhalt setzt diesen Timer zurück.
- Das Ungebundene Energie System löst das Reagenzien Zurück System nach dem Töten ab

General Bug Fixes
- Farbe der Unterhemden in der FN Kiste sind nun zufälliger Farbe
- Rüstungswert Anzeige berechnet nun neu, wenn ein Spieler im Rang bei den Rebellen auf/ab steigt
- Quest Gegenstände mit defekter Beschreibung bleiben nun nicht mehr, wenn das Quest fehlschlägt
- Monster teleportieren nun rein/raus aus der Arena in Tos, wenn ein Kampf startet/endet. 
- Kraft des Lichts und Schlachtfeld fix beim Ausstieg/Zuschauer Modus
- Performance Problem Fix (Client Lag) bei Eisstern und Feuersturm
- Fix beim Bardenbrief (Event Item)
- Fix beim Schattenform Verteidigungswert beim Raumwechsel
- Artefakt/Totem Fix beim Tragen eines Schildes
- Erdbeben Fix bei dem Minions den Meister angegriffen haben
- MiniMap Punkt beim Ausstieg korrigiert
- Fix für ein paar Quests die immer wieder defekt waren
- Ein paar Fehler in Maps behoben, bei dem Spieler hängen bleiben konnten
- Klassischer Client Fix, dass z.B. Zeilenumbrüche in Mails vom OGRE Client nicht richtig angezeigt wurden
- Loadout/Set Rollen Stacks zerfallen nicht komplett wenn ein ungegildeter Spieler versucht diese zu nutzen (nur noch eine)

**Comment by Arantis** [comment]
Noted it somewhere else
