### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by Arantis** [Arantis/Meridian59_112#18]
Ein paar Übersetzungsverbesserungen die ich bekommen habe in Rohform:
#1 Den Text wenn Magische Bombe gezündet wird, musst Du bitte auch mal ändern.
#2 Reparieren Text:

Teile von Das Langschwert verbinden sihc miteinander, um eine neue Einheit zu bilden.
#3 Alle Texte, die als Antwort auf die Frage wie die Ratsmitglieder stehen kommen.
#4 Du konzentrierst Deinen gesamten Willen auf den Zauberspruch Schattenform.

Dein Körper prickelt voll magishcer Energie. .......  magischer .....
#5 Die Beschreibung stimmt komplett nicht.

Es sollen wohl 2 ungeschliffene Seraph und 1 Feuersand sein.
#6 Von: Afiera Xor

An: 
Betreff:  Edelstein polieren
## Datum: Mon Mär 21, 2016 05:26

Vergiss die ungeschliffenen Edelsteine, ich habe welche von jemandem anderes bekommen. Danke.
---->  von jemand anderem .... 
#7 [###] Aina wurde gerade von ein Feier speiendes Kaninchen getötet.

soll doch bestimmt Feuer heißen
#8  Das Emblem einer Faust welche ein Kreuz hält ist auf dem Knauf zu sehen, und verspricht einen ein leuchten Vorteil im Kampf für die Gerechtigkeit.
#9 Dein Schrumpfkopf plappert, "Deine Gedult hat sich wirklich ausgezahlt...."

---> Geduld <--- nicht Gedult
#10

**Comment by Arantis** [comment]
ghostItem_name_rsc = de "Illusionärer Gegenstand"
ghostItem_desc_rsc = de \
   "Ein unwesentliches Bild sitzt auf dem Boden. Die Illusion scheint ein "
   ""

<--- da fehlt was ... im englischen

   ghostItem_desc_rsc = \
      "An insubstantial image sits on the ground, unable to be picked up.  "
      "The illusion appears to be %s%s."

**Comment by tyras2** [comment]
An insubstantial image sits on the ground, unable to be picked up.  The illusion appears to be a orc pit boss head.

**Comment by tyras2** [comment]
Kann geschlossen werden
