### ISSUE TITLE
Zauberschule Jala. Sprüche in Webseite Sortieren

### ISSUE THREAD

**Issue by Rodrigez01** [Arantis/Meridian59_112#18]
Zirkel 1
Frohsinn
Stärkung
Traurigkeit
############################################
Zirkel 2
Verzögerung
Kraanan bannen
Faren bannen
#############################################
Zirkel 3
Wiederherstellen
Tränke mixen
Qor bannen
Shal*ill bannen

#############################################
Zirkel 4
Jala Bannen
Wahrheit
Zwingtanz

#############################################
Zirkel 5
Magie bannen
Regeneriern
Zaubereffizienz

#############################################
Zirkel 6
Mana Kristalisieren

**Comment by tyras2** [comment]
@Rodrigez01 Gibt es die HP begrenzung wirklich? Habe alles mit meiner Mule kaufen könen..

**Comment by Rodrigez01** [comment]
wird verifiziert
