### ISSUE TITLE
Übersetzungsfehler (Sammelthread)

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#2]
Hier Sammeln wir die Übersetzungfehler:

**Comment by tyras2** [comment]
> XY motivierender Song, lässt dich, deine Müdigkeit vergessen.

Die zwei Kommata müssen weg

**Comment by tyras2** [comment]
> XY murmelt etwas  vor sich hin und führt eine geheimnisvolle Geste aus.

ändern in:

> XY murmelt etwas vor sich hin und führt eine geheimnisvolle Geste aus.

Da ist ein Leerzeichen zwischen "etwas" und "vor" zu viel

**Comment by tyras2** [comment]
> Your standing with The Minions of Life has decreased
> Your standing with The Minions of Death has increased

Fehlt komplett

**Comment by tyras2** [comment]
>Hanla zax'Ta hat dich beauftragt eine Feder eines Avar Schamanen zu besorgenSuche und töte solange Avar Schamanen bis Du eine Feder bei der Leiche findest.

ändern in

>Hanla zax'Ta hat dich beauftragt, eine Feder eines Avar Schamanen zu besorgen. Suche und töte solange Avar Schamane, bis Du eine Feder bei der Leiche findest.

**Comment by tyras2** [comment]
> Farens ;Agoe erfüllt den Raum mit Hitze, die alle Rüstungen schmelzen lässt.

änder in

> Farens Kraft erfüllt den Raum mit Hitze, die alle Rüstungen schmelzen lässt.

**Comment by tyras2** [comment]
> Huital ko'Nosak sagt, "Sei GegrÃ¼ÃŸt. Wir hoffen, dir gute Dienste zu leisten, denn ihre Wertsachen sind bei uns sicher."

ändern in

> Huital ko'Nosak sagt, "Sei Gegrüßt. Wir hoffen, dir gute Dienste zu leisten, denn ihre Wertsachen sind bei uns sicher."

**Comment by tyras2** [comment]
> Ruft eine Kreatur herbei, die ein Ebenbild Deiner selbst ist. Beachte, dass Du für alle Taten Deiner Reflektion verantwortlich bist und dass diese ausgesprochen schwer zu kontrollieren ist. Nimm Feuersand, Regenbogenfarne und ungeschliffene Seraphyme dafür.  

Zauber Spiegelbild: Da stimmen die Reas nicht, das sind doch nur Feuersand und Seraphyme?

Ändern in:

> Ruft eine Kreatur herbei, die ein Ebenbild Deiner selbst ist. Beachte, dass Du für alle Taten Deiner Reflektion verantwortlich bist und dass diese ausgesprochen schwer zu kontrollieren ist. Nimm Feuersand und ungeschliffene Seraphyme dafür.

**Comment by tyras2** [comment]
> Als Du den Raum betrittst, merkst Du, dass mächtige Energien vorhanden sind, undes sehr gefährlich sein kann sich hier aufzuhalten. Du spürst, dass du aus der Realitätgerissen wurdest und es hier keine Unterwelt gibt.

Ändern in:

> Willkommen in der Survival Arena! Als Du den Raum betrittst, merkst Du, dass mächtige Energien vorhanden sind. Es kann sehr gefährlich sein, sich hier aufzuhalten. Du spürst, dass du aus der Realität gerissen wurdest und es hier keine Unterwelt gibt.

**Comment by tyras2** [comment]
> Dein Körper prickelt voll magishcer Energie.

Ändern in

> Dein Körper prickelt voll magischer Energie.

**Comment by tyras2** [comment]
> Dein aktueller Schattenform Zauber fügt 10 Verteidigung gegen Monster hinzu.  Gegen Spieler normalem Level, fügt er 10 Verteidigung hinzu.

Ändern in

>Deine aktuelle Schattenform fügt X Verteidigung gegen Monster, und X Verteidigung gegen Mitspieler hinzu.

**Comment by tyras2** [comment]
> Du steigst aus deiner Existenz aus, zuversichtlich, dass Du das für weiter 480 Sekunden kannst.

Ändern in

> Dein Körper befindet sich nun auf einer anderen Bewußtseinsebene. Du hast nun 480Sekunden Zeit, wieder zurück zu kehren. Sollte dies dir nicht gelingen, musst du mit einer Strafe rechnen.

**Comment by tyras2** [comment]
> Vertigo

Der Zauberspruch Vertigo wurde nicht übersetzt, oder war das absicht?

> Verwirren

**Comment by tyras2** [comment]
> illusions wunden

Heisst laut RDE eigentlich: 

> Vorgetäuschte Wunden

**Comment by Arantis** [comment]
Erledigt im neuen Patch + noch einige andere.
