### ISSUE TITLE
Patchnotes 1.3

### ISSUE THREAD

**Issue by Arantis** [Arantis/Meridian59_112#20]
Generelle Änderungen
- Wieder einmal eine große Anzahl von Übersetzungen verbessert
- Die benötigten Reagenzien werden nun in der Zauber Beschreibung angezeigt
- Maximale Lagermenge von 100 auf 300 erhöht
- Gildenhallen Kisten: Holzkiste von 15000 auf 40000 Einheiten erhöht
                     Metallkiste von 21000 auf 60000 Einheiten erhöht
- Kisten in gemieteten Räumen von 9000 auf 15000 Einheiten erhöht
- Panzermolche geben nun 150 Lebenspunkte und ein Karma von -100
- Natterwürmer bringen euch nun bis auf 130 Lebenspunkte
- Mehr Skelette spawnen nun in der Halle im Schloß Victoria
- Spieler unter 50 Lebenspunkten verlieren nun keine Gegenstände mehr beim Tod
- Neue Einstellung, dass es uns möglich macht Artefakte öfter spawnen zu lassen
- Spezialwaffen mit Reinigungseffekt haben nun eine Zauberkraft von 60 anstatt einer zufälligen Kraft von 25-75
- Jegliche Zauber mit Zonen oder mit mehreren Zielen hat nun keinen Fraktionsverlust mehr zur Folge.
  Dies gilt für Radiuszauber, Raumzauber, Flash, Illusionen Auflösen, Stören, Mana Bombe, Letztes Sakrament, Erdbeben und Eisstern
- Attacken von Minions (Spiegelbild etc.) führen nicht mehr zum Fraktionsverlust solange es nicht vom Meister dazu gezwungen wurde (direkte Attacke)
- Wandzauber (Feuerwand etc.) führen nicht mehr zum Fraktionsverlust

Neues Erfahrungspunkte System
- Der Balken für die Chance einen Lebenspunkt zu erhalten (unter Ausdauer) hat nun zwei Anzeige Optionen
  Zum einen könnt ihr die % die ihr zum nächsten Lebenspunkt bereits geschafft habt anzeigen lassen, oder aber die XP die ihr habt, und noch benötigten
- Die Einstellungen könnt ihr in euren Voreinstellungen ändern. Standard ist XP erhalten / XP benötigt
- Wenn ihr mit der Maus über das XP (Erfahrungspunkte) Icon geht, wird euch angezeigt wieviele Erfahrungspunkte euer Character insgesamt besitzt
- Jeder Character hat bereits die passenden XPs für den aktuellen Character bekommen
- Es gibt nun Spezial Gegenstände, die gefunden werden können, die einen XP Bonus beim Töten geben (Rüstungen, Schilde, Handwaffen)
- Diese Spezial XP Gegenstände können selten, aber bei jedem Monster gefunden werden. Stärkere Monster lassen allerdings Gegenstände mit höherem XP Bonus fallen
- Monster geben eine Standard Menge an XP, egal welches Level sie haben (Skelette z.B. 75)
- Die XPs die man bekommt hängen von der eigenen Konstitution ab (wie zuvor auch)
- Ist man "zu stark" für das Monster, gibt es nur noch die Standard XPs
- Wenn ein Spieler das Monster nicht tötet, aber mit dagegen gekämpft hat, bekommt derjenige 66% der normalen Menge an XP
- Tötet man ein Monster in der Gruppe, bekommt man 25% der XP, die man normalerweise alleine von dem Monster bekommen würde
- Monster die nur etwas schwächer sind als der Spieler geben immernoch 10% der XP 
- Charakter mit einem Schutzengel (unter 50HPs) erlaten +10% XP
- Beim Tot verliert man nun XP anstatt direkt einen HP zu verlieren
- Spieler verlieren 20% von deren momentanem maximal erreichbaren XP in dem derzeitigen Level
- Fallen die XP dadurch unter 0 verliert man einen Lebenspunkt
- die Gesamtmenge der erreichbaren XP bezieht sich auf die maximal erreichbaren Lebenspunkte je Character
- Spieler mit der maximalen XP oder die, die darüber sind sollten nicht den Konstitutions-Grundwert ändern (Das altertümliche Schmuckstück), da sonst die XP auf das neue HP/Level angepasst wird.

Patcher / zukünftige Updates
Wir haben uns dazu entschlossen das derzeitige Patcher tool zu ersetzen bzw. nur noch als Alternative zu nutzen. Es gab immer wieder Probleme mit dem Patcher und Updates, die wir durchgeführt haben.
Außerdem haben wir des Öfteren Kompatibilitätsprobleme gesehen bei der Installation des Patchers.

Ab diesem Patch ist es nun wieder möglich, einfach das Spiel ansich zu starten, und es prüft ab, ob ihr den aktuellen Patch besitzt oder nicht. 
Dies ist eine Kombination vom ganz alten Patcher sowie vom Derzeitigen, und ihr müsst nichts weiter tun.

Für die zukünftigen Patches gibt es also nun 2 Möglichkeiten.
#1 Patchen mit dem Patchertool
- Startet das Patchertool 
- klickt auf Update/Install
- danach könnt ihr wie gewohnt spielen
#2 Patchen mit dem Meridian59 Client
- ihr habt bereits eine Verknüpfung der Meridian.exe, oder startet die Meridian.exe eh immer anstatt dem Patcher (nur beim Patchen)?
- dann könnt ihr beim nächsten Patch einfach diese Meridian.exe oder Verknüpfung starten, und beim Login wird euch angezeigt, dass ein neues Update vorliegt
- bestätigt dieses, und er startet den "altbekannten" Client Patcher von Meridian und nachdem dieser fertig ist könnt ihr euch direkt wieder einloggen

Dieser Patcher funktioniert allerdings derzeit nur für den klassischen Client. Der 3D Client muss Stand heute noch mit dem Patcher aktualisiert werden.
Wir versuchen aber auch das bis zum nächsten Patch in den 3D Client selber einzubauen, damit das Patchertool gänzlich wegfallen kann.

Falls hierzu noch weiterführende Fragen sind z.B. wie man eine Verknüpfung der Meridian.exe anlegt, könnt ihr uns gerne anschreiben.

Derzeitige Dinge, an denen wir arbeiten:
- Justiz System (wir bauen derzeit zumindest als Alternative/Option das alte System wieder ein), somit können wir ab dann selber entscheiden, welches wir wollen und es ggf. anpassen
- Neuer 3D Client Patcher  (siehe Post Patcher)
- 3D Client in deutsch wird zeitnah erscheinen (wir sind nahe vor dem Release, aber haben noch 1-2 kleine Probleme nicht gelöst)

**Comment by tyras2** [comment]
Update 1.3

Bei diesem Update haben wir uns auf zwei wesentliche Änderungen von Meridian konzentriert.

Bei der Aktualisierung der Clients waren wir bisher immer auf das System des Patchers vom Open-Meridian Projekt aus der USA abhängig. Dieser war wirklich sinnvoll für das Updaten von mehreren Servern, hatte jedoch einige schwächen und war nicht immer zu 100% funktionstüchtig. Daher haben wir uns nun dazu entschlossen, diesen Patcher zu entfernen und künftig wie gewohnt über den Client selbst zu aktualisieren. Dieses System des Updates haben wir weiterentwickelt und ist nun für den User deutlich besser, da es beim Start des Client automatisch, ohne das verwenden eines externen Patchers, auf Updates prüft und dieses vornimmt. So ist es uns also nun möglich, auch kleinere Updates/Bugfixes zeitnah ohne Vorankündigung vorzunehmen.

In Zukunft müsst Ihr also den Client, wie aus der Vergangenheit gewohnt, direkt über die meridian.exe starten. Eine Verknüpfung auf die meridian.exe auf den Desktop oder in die Startleiste ist natürlich weiterhin möglich.

Solltet Ihr weitere Fragen dazu haben, wendet euch gerne an das gesamte meridian59.de Team

Die zweite wesentliche Änderung betrifft das HP/XP System. Das alte System war einzigartig in der Welt der Rollenspiele, doch es war nicht immer einfach zu verstehen. Das neue System macht nun ganz klar deutlich, wieviele Tötungen eines Monster nun benötigt werden, um ein HP zu erhalten. Weitere Informationen dazu findet ihr unten in den Patchnotes.

Generelle Änderungen:
- Wieder einmal eine große Anzahl von Übersetzungen verbessert.
- Die benötigten Reagenzien eines Zaubers werden nun in der jeweiligen Beschreibung angezeigt.
- Auf Wunsch der Community wurde die maximale Lagermenge von 100 auf 300 Einheiten erhöht.
- Konzentration beim Zauber Lähmen dauerhaft deaktiviert.
- Kisten in den Gildenhallen: Holzkiste von 15000 auf 40000 Einheiten erhöht, Metallkiste von 21000 auf 60000 Einheiten erhöht.
- Kisten in gemieteten Räumen von 9000 auf 15000 Einheiten erhöht.
- Panzermolche geben nun 150 Lebenspunkte und ein Karma von -100
- Natterwürmer bringen euch nun bis auf 130 HP.
- Der Spawn von Skeletten im Schloß Victoria wurde erhöht. Dabei wurde auch ein Bug ausgebessert, bei dem es zu Perioden gekommen ist, bei welchen keine Skelette mehr aufgetaucht sind.
- Spieler unter 50 HP verlieren nun keine Gegenstände mehr beim Tod.
- Neue Einstellung integriert, dass es uns ermöglicht, den Spawn von Artefakte anzupassen oder die Zeit zwischen Skandalen zu verändern. Möglich ist auch eine Option, bei der die Artefakte schneller erscheinen, wenn die Anzahl der User auf dem Server erhöht ist.
- Spezialwaffen mit Beseitungseffekte haben nun eine Zauberkraft von 60%, anstatt einer zufälligen Zauberkraft von 25 bis 75%. Die Einstellungen hierzu können nun jederzeit angepasst werden.
- Jegliche Zauber mit Zonen-Effekten oder mit mehreren Zielen hat nun keinen Fraktionsverlust mehr zur Folge. Dies gilt für Radiuszauber, Raumzauber, Lichtblitz, Illusionen Auflösen, Stören, Mana Bombe, Letztes Sakrament, Erdbeben und Eisstern.
- Attacken von Spiegelbilder führen nicht mehr zum Fraktionsverlust, solange es nicht vom Meister dazu gezwungen wurde (direkte Attacke).
- Wandzauber (Wie zB. Feuerwand) führen nicht mehr zum Fraktionsverlust.
- Gesetzlose oder Mörder verlieren nun bei Angriff nicht mehr Ihre Fraktion.

Das neue Erfahrungspunkte (XP) System:
- Der Anzeige für die Chance einen Lebenspunkt zu erhalten, hat nun zwei verschiedene Varianten zur Auswahl. Zum einen könnt Ihr die Anzahl der benötigten XP bis zum nächsten HP in Prozent ausgeben lassen, oder ihr könnte die Anzahl der Erfahrungspunkte in einem festen Wert ausgeben lassen (123 XP von 456XP).
- Die Einstellungen könnt ihr in euren Voreinstellungen ändern. Standard ist die Ausgabe in einem festen Wert.
- Wenn ihr mit der Maus über das XP (Erfahrungspunkte) Icon geht, wird euch angezeigt, wieviele Erfahrungspunkte euer Character insgesamt schon errungen hat.
- Monster geben immer eine feste Menge an XP pro Tötung (Abhängig von den HP’s der Monster, so geben Ratten 30 XP, Skelett dagegen 75 XP).
- Die XP, welche man zusätzlich zu dem Basis Wert erhält, hängt von der Konstitution ab (Identisch zum alten System). Hat man also eine höhere Konstitution, erhält man pro Tötung mehr XP. 
- Es gibt nun neue Gegenstände, die einen XP Bonus beim Töten geben. Dazu zählen unter anderem Rüstungen, Schilder und Waffen.
- Diese Spezial XP Gegenstände können wirklich selten, aber bei jedem Monster gefunden werden. Stärkere Monster lassen allerdings Gegenstände mit einem höherem XP Bonus fallen.
- Wenn ein Spieler das Monster nicht tötet, jedoch gegen diese gekämpft hat, bekommt man 66% der normalen Menge an XP (Wenn man z.B. nicht den letzten Schlag bekommen hat).
- Tötet man Monster während dem man sich in der Gruppenbildung mit Freunden befindet, bekommt man 25% der XP von jedem getöteten Monster im Raum.
- Monster, die nur bis 5 HP schwächer sind als der Charakter, geben 10% der normalen XP.
- Charakter mit einem Schutzengel (unter 50 HP) erhalten zusätzlich 10% XP.
- Beim Tot verliert man nun XP anstatt direkt ein HP zu verlieren. Gestorbene Spieler verlieren nun immer 20% der XP in dem derzeitigen HP Level. Fallen die XP dadurch unter 0 verliert man ein HP.
- Die XP werden nun auch nach dem erreichten maximalen HP’s mitgezählt, und können sich so möglicherweise über den ein oder anderen Bonus freuen.
- Spieler mit der maximalen Anzahl von HP’s sollten kein altertümliche Schmuckstück benutzen, um die Konstitution zu senken, da sonst die XP auf das neue HP/Level angepasst wird!

Bug Fixes:
- Die Anzahl der eingelagerten Gegenstände wird nun korrekt ermittelt.
- Bug beseitigt, das Illusionierte Monster ohne Abfrage der Sicherheitseinstellung beseitigt hat.
- Bug beim Abspielen der Sounds bei Benachrichtigung von Mitteilungen.

Natürlich wollen wir euch auch gerne einen kleinen Einblick an die weiteren Arbeiten rund um das nächste Update geben. So Arbeiten wir gerade daran, wieder das alte Justiz System zu integrieren. So können wir künftig darüber gerne eine kleine Abstimmung starten, ob wir das neue Justiz-System behalten, oder wieder auf das alte zurückgreifen.

Der neue 3D-Client wird Zeitnahe auch in Deutscher Sprache veröffentlicht, wir haben jedoch einige Kleinigkeiten noch nicht Lösen können, so müsst Ihr euch leider noch etwas gedulden.

Für Anregungen für künftige, oder auch dieses Update, sind wir natürlich immer offen.

LG
Arantis
