### ISSUE TITLE
Teamspeak 3 Server 125 Plätze

### ISSUE THREAD

**Issue by Rodrigez01** [Arantis/Meridian59_112#20]
Hätte einen TS3 Server mit 125 Plätzen, Erweiterbar auf 500
Vieleicht schauen wir mal ob Bedarf besteht ?!?

**Comment by tyras2** [comment]
Können wir ja mit in die Willkommensmeldung nehmen, dann kann das jeder nutzen, der es möchte?

Schick mal die Daten rüber..

**Comment by Rodrigez01** [comment]
Meridian59.org:55554

**Comment by tyras2** [comment]
Kannst du das vielleicht irgendwie auf meridian59.de umleiten?

**Comment by Rodrigez01** [comment]
nein. 
es würde nur über eine Subdomain gehen die Arantis auf meinee IP Adresse verlinkt ..
83.169.12.224
oder wir nehmen nur die IP

83.169.12.224:55554

**Comment by tyras2** [comment]
@Arantis Kannst du das in die Willkommensmeldung mit rein nehmen.. Ganz untern

> Willkommen auf Server 112 - der Offizielle Meridian59 Server in Deutschland!

News: Aufgrund der Zahlreichen neuen Charaktere im Lande, haben sich die 5 Ratsmiglieder Meridians dazu entschlossen, ein Göttliches Wochende auszurichten. Mehr zu dem Event am kommenden Wochenende findet Ihr in den Nachrichtenkugeln.

Für alle Meridian haben wir einen Teamspeaker-Server unter folgender IP eingerichtet: 83.169.12.224:55554

**Comment by Rodrigez01** [comment]
## Der Streitkolben

>Obwohl sie tödlich aussieht, ist die Wirkung dieser Waffe nur gering. Die eingesetzten Nägel wurden aus weichem Metall hergestellt, ihr Schaft ist dünn und zerbrechlich.  The craftsmanship of this Der Streitkolben is admirable, obviously the result of hundreds of hours of work by expert hands.

## Folgt
