### ISSUE TITLE
Globe

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#21]
Hallo Meridianer,

in den letzten Tagen ist es etwas ruhig um die Arbeit des Admin-Teams geworden, daher wollen wir euch einen kleinen Zwischenbericht darüber geben, was in den letzten 20 Tagen nach dem letzten Update auf Server 112 passiert ist.

Noch immer ist das Installieren und das Aktualisieren von Meridian59 eines der Problemen, auf das sich das Entwicklerteam in den letzten zwei Wochen konzentrieren musste. Mit der letzten Veröffentlichung hatten wir bereits eine Version des ursprünglichen Ingame-Updater integriert. Diesen haben wir nun nochmal wesentlich verbessert, so das unter anderem auch fehlerhafte Dateistrukturen erkannt werden, oder abgebrochene Updates erneut startet. Im Detail steckt natürlich noch einiges mehr dahinter.

Viel Arbeit mussten wir in den neuen 3D-Client stecken. Dieser hatte bisher überhaupt keine Möglichkeit, ein Ingame-Update vorzunehmen. Hier konnten wir nun ein identisches System zum Classic-Client erfolgreich integrieren.

Auch ein neues Installationsprogramm steht in den Startlöchern, das mit einem einfachen Doppelklick auf die Installationsdatei von Meridian59 die aktuellste Version installiert und gewünschte Verknüpfungen erstellt.

Das ganze hat leider viel wertvolle Zeit gekostet, die wir lieber und vor allem intensiver in das Gameplay gesteckt hätten. Doch wir glauben, es war mehr als notwendig, um auf langer Sicht mehr Spieler für Meridian zu begeistern.

Große Fortschritte können wir auch in unserem Wiki (wiki.meridian59.de) vermelden. Wir haben schon viele Inhalte aktualisieren können, und Arbeiten mit Hochdruck daran, schon bald eine komplette Plattform mit vielen Gameplay-Informationen rund um Server 112 anbieten zu können.

Wir befinden uns nun in den letzten Zügen, und hoffen, das neue Update am Wochenende einspielen zu können. Anschließend werden wir uns wieder voll und ganz auf das Gameplay konzentrieren, und haben bereits tolle Ideen für Endgame-Inhalte sowie die Rekrutierung von neuen Mitspielern.

Solltet auch Ihr Verbesserungsvorschläge haben, oder einfach nur eine tolle Idee rund um Meridian59, würden wir uns freuen, von euch zu hören. Sei es in der Nachrichtenkugel, per Mail (support@meridian59.de) oder in unserem IRC-Chat. Denn nur mit eurer Hilfe können wir Meridian wieder zu dem machen, was es verdient!

**Comment by Arantis** [comment]
posted!
