### ISSUE TITLE
Übersetzung die 2te

### ISSUE THREAD

**Issue by Rodrigez01** [Arantis/Meridian59_112#22]
Zauber Reparieren

>Teile von Der Ork-Schild verbinden sihc miteinander, um eine neue Einheit zu bilde

Richtig ist 

>Teile von Der Ork-Schild verbinden sich miteinander, um eine neue Einheit zu bilden

**Comment by Rodrigez01** [comment]
im Pfad kod/object/aktive/holder/room/crnthrm/coruniv.lkod
 da stehen alle Bücher drin

Schachquest ist \kod\object\passive\questtemplate\chessqt.lkod

**Comment by tyras2** [comment]
> Teile von Der Ork-Schild verbinden sich miteinander, um eine neue Einheit zu bilden

**Comment by tyras2** [comment]
> scroll of set

>This scroll will register your inventory preferences with Frular's office, allowing you to use scrolls of loadout to re-equip yourself from your guild hall chests at a distance.

This parchment encodes 1 mystic incantation.  The runic script averages 45 spellpower.

Ändern in:

> folgt

> folgt

**Comment by tyras2** [comment]
> scroll of loadout

> This scroll will activate your link with your guildhall chests, magically acquiring gear according to your preferences registered with Frular's office. The magic will only function in a safe environment, and then only for guild members rank two or above.

Ändern in:

>folgt

>folgt

**Comment by Rodrigez01** [comment]
## Der Streitkolben

>Obwohl sie tödlich aussieht, ist die Wirkung dieser Waffe nur gering. Die eingesetzten Nägel wurden aus weichem Metall hergestellt, ihr Schaft ist dünn und zerbrechlich.  The craftsmanship of this Der Streitkolben is admirable, obviously the result of hundreds of hours of work by expert hands.

## Folgt

**Comment by Rodrigez01** [comment]
>Huital ko'Nosak sagt, "Sei GegrÃ¼ÃŸt. Wir hoffen, dir gute Dienste zu leisten, denn ihre Wertsachen sind bei uns sicher."

>Huital ko'Nosak sagt, "Sei Gegrüßt. Wir hoffen, dir gute Dienste zu leisten, denn ihre Wertsachen sind bei uns sicher."

**Comment by tyras2** [comment]
Wurde glaube schon korrigigiert, hatte ich schon gepostet @Arantis  ?

**Comment by Rodrigez01** [comment]
Hihi,
Das magische Schwert
>Alte Runen zieren diese schöne Waffe, eine leichte Klinge von unübertroffener Güte. Kraanans Segen umgibt dieses Schwert. Nahezu unsichtbare Ströme führen an der Seite der Glinge her.

>Alte Runen zieren diese schöne Waffe, eine leichte Klinge von unübertroffener Güte. Kraanans Segen umgibt dieses Schwert. Nahezu unsichtbare Ströme führen an der Seite der Klinge her.

**Comment by Arantis** [comment]
erledigt soweit kann geschlossen werden. Nach dem Patch testen wir die gefixten SAchen

**Comment by tyras2** [comment]
@Rodrigez01 Bitte schließen
