### ISSUE TITLE
Wiki Fehler

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#25]
- Spezialwaffen Übersetzen

**Comment by tyras2** [comment]
* Spezialwaffen müssen auf Deutsch übersetzt werden
http://wiki.meridian59.de/artikelanzeige,8,21,Tipps%20und%20Tricks,5,87,122,0,Spezial%20Waffen.html

**Comment by Arantis** [comment]
bis auf Spezialwaffen erledigt soweit...

**Comment by tyras2** [comment]
Ränge der Soldaten anpassen

**Comment by skittles1** [comment]
On the page with the weaponcraft skills: (http://wiki.meridian59.de/index.php?show=schule_direct&s_link=1&o_id=8&h_id=46&h_name=Schulen%20und%20Fertigkeiten&s_meng=20&s_id=170&start=0&u_name=Waffenfertigkeiten)

Second wind says it is sold by Cylill, should say Drechx.

**Comment by tyras2** [comment]
Kleinere Heilung, Dunkelheit, Tod Vortäuschen und Stärkung frei von Reagenzien.

**Comment by tyras2** [comment]
Licht (?) auch frei

**Comment by Arantis** [comment]
add new items (kocatan fruit e.g.)
