### ISSUE TITLE
Ich für mein Teil bin raus ..

### ISSUE THREAD

**Issue by Rodrigez01** [Arantis/Meridian59_112#29]
ich mach jetzt doch mein eigenes Ding

**Comment by tyras2** [comment]
Schade, das du dich für diesen Schritt entscheidest. Ich kann es nicht nachvollziehen

Dürften wir erfahren, warum?

**Comment by Rodrigez01** [comment]
klar,
1. ich finde es bescheiden, wie Du "Tyras" Dich mit deinem Char Profilierst.
    meiner Meinung nach, hat ein "Sterblicher" Char NICHT das Recht sich mit einem "Barden" zu     
    verknüpfen. warum? Ganz einfach, Weil Du nicht mehr Autark bist. Du könntest Deine Chars mit  
    Hilfe des Barden hochgezogen haben. Und bei einem Krieg oder sobald Du jemanden tötest, es Ärger gibt ...und viele Gründe mehr ....

2. Ist aber nur meine Meinung, Ein Barden mit dem Namen Barde ist Mist. aber wie gesagt das ist 
    nur meine Meinung 

3. Ich habe gedacht, wir sind ein Team, naja bis gestern hatte ich es gedacht. Aber es geht alles an 
   mir vorbei. Ich wollte am Wochenende das Video drehen .. aber wie immer ist das gekonnt 
   überhört worden... aber egal .. ich habe DAZU wenig Lußt

und es gibt noch einige Gründe die ich hier nciht unbedingt los werden muss ...

**Comment by tyras2** [comment]
Genau darum wollte ich einen externen Barde einstellen, um diese Vorurteile garnicht erst aufkommen zu lassen! Somit bestätigst du meine Vermutung.

1) Wie du aber sicherlich weisst, kann der Barde soviel, wie ein 20HP Char aus Raza. Der Barde ist nur dazu da, Events anzukündigen, ob per Mitteilung oder in den Nachrichtenkugeln. Ich logge mich nur dafür ein, sonst nie. Das Kannst du sicherlich bestätigen..

2) Der Barde bekommt bei richtiger Besetzung einen richtigen Namen.

3) Wieso geht alles an dir vorbei? Das Event war doch als Github hier in den Issues? Abgesprochen haben wir uns kurz vor dem Event in IRC. Daher kann ich das nicht nachvollziehen, warum du dich ausgeschlossen gefühlt hast.

Schade das du dich für diesen Schritt entschlossen hast, trotzdem viel Glück

2) Ein zukünftiger Barde bekommt einen richtigen Namen. Es gibt halt leider noch keinen.

3)
