### ISSUE TITLE
Translation todo:

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#30]
ToDo

**Comment by Arantis** [comment]
[###] Marvella ist gerade gestorben. avar shaman war zu stark.
-- deutsche Übersetzung fehlt bei "avar shaman"

Ein Fläschchen mit Parfum:  Ein Schluck von dieser modrig riechenden Flüssigke...
--- Text ist abgeschnitten

**Comment by tyras2** [comment]
* Sooo mal ein paar Fehlerteufel gefangen      Wenn ich den Zauber "Schirm" ausführe, habe wir da nen Zungenbrecher vor dem Wort "Licht"  ...... Du erweiterst deine Fingerspitzen mit einer Kuppel voller mystischem, schimmerndm Licht.
Du fühlst, dass dich die Energie des Schirms schützt (bitte noch ein "e" hinterher werfen  )

* In der Beschreibung vom Riija-Zauber Zirkel 4 >>Wunden ignorieren<<   brauchen wir für den Zauber "zweiund" -  also "zweiund" Feuersand 🙂  ..... hier bitte die Leerstelle mit der Post schicken 🙂

* Da habe ich ja noch nen Fehlerteufel ...... Afiera Xor in Jasper leidet an Vergesslichkeit, die ihn langsam verblöden lässt !    oder verblödet er bei der ganzen Vergesslichkeit , weil er zu oft verwirrt wird ?   Ich will den Zauber "Verblöden" Zirkel 4 Riija erwerben, wenn ich dann die Prozente entlich zusammen habe, brabbelt Afiera Xor von "Vergessen" .... bitte bei ihm  für ausreichend Wasser und Nährstoffe sorgen - sonst wird der alte Herr noch vollständig GAGA !

* ..... da noch eine ?? Fehlermeldung ?? ... müsste aber erstmal die letzte sein  ....... Kraanan-Schüler-Quest ...... wird bei Priesterin Qertina geholt und eingelöst ..... NPC usw. alles ok .. aber in der Beschreibung wird immer noch der alte Name mit dem Psydo-Apostroph geschrieben .... früher hat Meridian angeblich das >  '  << nicht zugelassen, aber irgend eine Einigung wäre doch mal schön, ob nun .... Qertina , Qertinya oder Qerti'nya   ist ja fast egal ... nur einheitlich sollte es ggf. ja doch mal endlich werden!  🙂   liebe Grüße von einem User, der immer etwas auszusetzen hat 🙂 ......

* einen habe ich noch:   Die heißgeliebte "Gelegenheitsquest"   wird eine Zeitlang vom NPC angeboten, wenn die Zeit um ist und man den NPC mit Hallo begrüßt, läuft das so ab:
Du sagst, "Hallo"
Moxal ix'Hanak begrüßt dich mit, "Hallo, Spielername! Du kommst gerade rechtzeitig. Etwas später und Du hättest eine großartige Gelegenheit verpasst."

* eil 2 der Meldung "Gelegenheit" ...... wenn die Quest NICHT mehr vergeben wird, weil man zu spät kommt, müßte der Text doch genau andersrum lauten:  
Du sagst, "Hallo"
Moxal ix'Hanak begrüßt dich mit, "Hallo, Spielername! Du kommst zu spät. Etwas früher und Du hättest nicht die großartige Gelegenheit verpasst."    ------>   oder ist der NPC Moxal ix'Hanak auch vollkommen GAGA und Riija hat ihn ebenfalls vergessen, verwirrt und verblödet ? .......

**Comment by Arantis** [comment]
..... kehrt aus seinem Ausstieg aus der Realität zurück! (männlich/weiblich)

**Comment by Arantis** [comment]
Betreff: Übersetzungsfehler
Datum: Son Okt 23, 2016 21:15
-------------
Schüler-Quest für Blitzschlag von Afiera Xor bitte überarbeiten:

Afiera Xor sagt zu Dir, "Ich kann Dir das Bisschen über die mystische Magie beibringen, was ich weiß. Dafür verlange ich einen Gefallen. Ich brauche dringend folgendes: Bringe Die Phiole mit Zuckerwasser zu Parrin Aragone, denn ich bin ihm ungern zu nah. Siehst Du, Parrin Aragone ist eines der letzten Wesen, die sich von der ungesunden Kraft menschlicher Energie ernährt. Ich weiß nicht mehr als das Parrin Aragone's Nähe einen schlechten Einfluss auf Dich hat. Triff ihn nur kurz, vielleicht kannst Du dadurch diesen Effekt vermeiden."

Parrin Aragone sagt zu Dir, "Danke, Darvin. Ich hoffe, dass Die Phiole mit Zuckerwasser mir helfen wird, den Effekt vor dem Du gewarnt wurdest, zu beseitigen. Geh jetzt! Es sei denn, du möchtest auch davon befallen werden?"

**Comment by Arantis** [comment]
toter Troll hat keinen Sinn, mit deiner Magie gebastelt zu werden.  <-- Illu geschöpf?

**Comment by Arantis** [comment]
Afiere Xor - ich fürchte ich habe zur Zeit nichts zu verkaufen

Afiere xor -.. Ah, Du bist von DEinem Auftrag zurückgekehrt.... " Komm wieder, wenn Du den "Vergessen" Zauber lernen willst

<-- bietet Verblöden an

**Comment by Arantis** [comment]
"Dieser Bar Gocker ist in einem ziemlich gutem Zustand."



Die Beschreibung der Bar-Hocker im fröhlihen Mönch :)

**Comment by Arantis** [comment]
Aufgebracht durch Feuerwand, "stampt" der Luppogg König feste auf dem Boden!


Aufgebracht durch Feuerwand, stampft der Luppogg König feste auf dem Boden!

**Comment by Arantis** [comment]
Having claimed Das Haupttor zur Stadt Tos, Außenbezirk von Tos, und Die Grenze zum Ödland, Prinzessin Kateriina now also controls the city of Tos!

**Comment by Arantis** [comment]
Jedes Jahr warten unedlich viele Kinder darauf unter dem Qormas Baum zu schauen,und zu sehen, welch schöne Todeswerkzeuge sie bekommen haben.

**Comment by Arantis** [comment]
Der Schneemann sieht eigentlich friedlich aus, aber irgendwas an ihm wekct das Gefühl in Dir das er böse ist.
