### ISSUE TITLE
Übersetzungs ToDo

### ISSUE THREAD

**Issue by Arantis** [Arantis/Meridian59_112#39]
mrelder.lkod
MrEl_entry_welcome = de \
   "Ein weitere Reisender in Meridian! Vielleicht kommt %s%s zu mir und erzählt "

**Comment by tyras2** [comment]
> XY Bezug zur Realität reißt  wird mit Gewalt an einen anderen Ort gebracht!
in
> XY Bezug zur Realität reißt ab und wird mit Gewalt an einen sicheren Ort gebracht!"

**Comment by tyras2** [comment]
> Nachdem Das Haupttor zur Stadt Tos, Außenbezirk von Tos, und Die Grenze zum Ödland, von Herzog Akardius eingenommen wurde wird nun auch die Stand von kontrolliert Tos!

Das Ende kling komisch

**Comment by tyras2** [comment]
> [###] XY von XY wurde von XY von XY im Gildenkampf abgeschlachtet.

3x "von", ließt sich komisch. Wie war es im Original?

**Comment by tyras2** [comment]
> Die Worte dieses Liedes bilden einen Zauber, der die Konzentrationsphase eines Zaubereres verlängert. Es wird lediglich eine Phase der Konzentration benötigt, um dieses Lied anzustimmen.  

in

> Die Worte dieses Liedes bilden einen Zauber, der die Konzentrationsphase eines jeden Zauberers verlängert. Es wird lediglich eine Phase der Konzentration benötigt, um dieses Lied anzustimmen.

**Comment by ThorsHammer666** [comment]
Posting Arantis ganz oben

Vorschlag:

"Ein weitere Reisender in Meridian! Vielleicht kommt %s%s zu mir und erzählt mir eine Geschichte"
oder
"Ein weitere Reisender in Meridian! Vielleicht kommt %s%s zu mir und erzählt uns etwas über sich selbst"

**Comment by tyras2** [comment]
"Die Kunst der Gebietseroberung"

Formatierung in diesem Buch (CN) fehlt komplett

**Comment by Arantis** [comment]
Hey Thors! Perfekt, einfach hier kommentieren und was dazu schreiben :)
Diese Issues werden dann geschlossen, wenn Sie umgesetzt werden/wurden bzw. der Patch dann eingespielt wird.

Danke!

**Comment by ThorsHammer666** [comment]
ah - ok .... danke für die Rückmeldung ... ich schau mal, was ich noch machen kann !

**Comment by Arantis** [comment]
erledigt - ist im Patch
