### ISSUE TITLE
Helferlein überarbeiten

### ISSUE THREAD

**Issue by tyras2** [Arantis/Meridian59_112#40]
Ich nehme an, das ggf viele Ingame Mailanfragen an unseren Helferlein gehen, die nie abgerufen werden. Kann man das irgendwie bei diesem Char deaktivieren? Oder ein Auto-Reply einbauen?

Das gleiche würde ich gerne für tells sehen, wie "Dieser Char ist mit unserem IRC-Support verbunden, solltest du keine Antwort erhalten, ist dieser z.Z. leider nicht besetzt."

**Comment by Arantis** [comment]
Gute Idee- mal schauen wie/ob da was geht.
